### PR TITLE
Support for local LLM models (Ollama) and petition for a more inclusive Name

### PR DESCRIPTION
**Pull request by devparanjay**
**Commit Message** -
`Added support for local models via Ollama, organized the program, added .env, added requirements.txt, and updated the README accordingly.`

**Name Change** -
_I request a change in name of the repo from "OpenAI-API-Terminal-Chatbot" to "Terminal Assistant" to better reflect the new changes, since the previous name won't apply with the support for Ollama._

### CODE REVIEW

**Review by stavrostzagadouris — APPROVED** [review]
Very cool @devparanjay, Thanks for cleaning it up and the added ollama support.

**Review by stavrostzagadouris — APPROVED** [review]

**Comment by devparanjay** [comment]
@jiberwabish Thanks! Useful and simple project I came across while exploring, so did what I could. 😄
I'm thinking of working on some small tweaks like easier customization of system prompts, etc. when I get time next.

**Comment by jiberwabish** [comment]
Sure. Go for it. I'm learning things from you already.

**Comment by devparanjay** [comment]
😁 Let me know if and when you get any other cool and useful ideas, maybe we can work on them together.

**Comment by jiberwabish** [comment]
Cool idea. Will do!

**Pull request merged**
